# Multi-stage build
# 1. Build stage
FROM maven:3.8.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -Dmaven.test.skip=true
COPY src ./src
RUN mvn package -DskipTests -Dmaven.test.skip=true -Dsurefire.skip=true

# 2. Run stage
FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
